server:
  port: 8080
  servlet:
    context-path: /trip

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip_doublejj?characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    password: ssafy
    username: ssafy
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant-path-matcher
logging:
  level:
    com:
      trip: debug

mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.trip